from ethdroid.config import NUMBER_WALLETS

# Russian language ('ru' and 'ru-RU')
RUSSIAN = {'TXT_USE_START_BUTTON': '🚀 Используй команду /start для начала работы с ботом!',
           'MENU_ADD_ETH_WALLET': 'Добавить кошелёк',
           'MENU_DEL_ETH_WALLET': 'Удалить кошелёк',
           'MENU_CHECK_ALL_BALANCE': 'Мой баланс',
           'MENU_BOT_OPTIONS': 'Настройки',
           'MENU_SHARE_BOT': 'Поделиться ботом',
           'MENU_FEEDBACK': 'Обратная связь',
           'TXT_USE_KEYBOARD': '📱 Используй клавиатуру бота, пожалуйста',
           'TXT_SHARE_BOT': 'Отправь ссылку на этого бота своим друзьям! 👇',
           'TXT_FEEDBACK': 'Напишите ваше сообщение для администратора:',
           'MENU_GO_BACK': 'Назад',
           'TXT_ERROR': '😓 К сожалению не могу отобразить информацию сейчас. Пожалуйста, попробуй позже!',
           'TXT_ADD_ETH_NAME_WALLETS_FULL': '🚫 Превышен лимит на ' + str(NUMBER_WALLETS) + ' *Ethereum кошельков*',
           'TXT_ADD_ETH_ADDRESS_WALLET': '➕ Введи адрес нового *Ethereum кошелька* 0x...',
           'TXT_ADD_ETH_ADDRESS_WALLET_WRONG': '🚩 Неправильный *Ethereum адрес*, попробуй другой 0x...',
           'TXT_ADD_ETH_ADDRESS_WALLET_EXISTS': '📌 Этот *Ethereum адрес* уже был добавлен ранее',
           'TXT_ADD_ETH_ADDRESS_WALLET_ADDED': '*✅ Ethereum адрес* успешно добавлен!\n',
           'LINK_SHARE_BOT': 'Поделиться ботом',
           'LINK_TEXT_SHARE_BOT': 'Всегда будешь в курсе баланса Эфириума и ERC токенов на твоих кошельках! 👍',
           'TXT_ETH_ADDRESS': '📌 *Ethereum адрес:* ',
           'TXT_ETH_TOKENS': '📎 *Tокены ERC*:',
           'TXT_ETH_TOKENS_EMPTY': '📎 *Нет ERC токенов*',
           'TXT_DEL_ETH_WALLET': '❌ Выбери *Ethereum кошелёк* для удаления:',
           'TXT_NO_ETH_WALLET': 'ℹ Нет ни одного *Ethereum кошелька*!',
           'TXT_WALLET_UPDATES': '👉 Изменение баланса:',
           'TXT_START_MSG': '👽 Привет, я твой ETHdroid Bot! Я помогу тебе быть в курсе '
                            'актуального баланса Эфириум и ERC токенов на твоих кошельках.'}

# Spanish language ('es' and 'es-ES')
SPANISH = {'TXT_USE_START_BUTTON': '🚀 ¡Utiliza el comando /start para empezar usar el bot!',
           'MENU_ADD_ETH_WALLET': 'Añadir cartera',
           'MENU_DEL_ETH_WALLET': 'Quitar cartera',
           'MENU_CHECK_ALL_BALANCE': 'Mi saldo',
           'MENU_BOT_OPTIONS': 'Ajustes',
           'MENU_SHARE_BOT': 'Compartir el bot',
           'MENU_FEEDBACK': 'Feedback',
           'TXT_USE_KEYBOARD': '📱 Usa el teclado del bot, por favor',
           'TXT_SHARE_BOT': '¡Comparte este bot con tus amigos! 👇',
           'TXT_FEEDBACK': 'Escribe tu mensaje para el administrador:',
           'MENU_GO_BACK': 'Atrás',
           'TXT_ERROR': '😓 Lo siento, ahora no puedo mostarte información. ¡Pruébalo más tarde por favor!',
           'TXT_ADD_ETH_NAME_WALLETS_FULL': '🚫 Está permitido añadir solo ' + str(NUMBER_WALLETS) + ' *carteras de Ethereum*',
           'TXT_ADD_ETH_ADDRESS_WALLET': '➕ Entra la dirección de tu *cartera de Ethereum* 0x...',
           'TXT_ADD_ETH_ADDRESS_WALLET_WRONG': '🚩 Esta *direccíon de Ethereum* no está correcta, pruebalo de nuevo 0x...',
           'TXT_ADD_ETH_ADDRESS_WALLET_EXISTS': '📌 Esta *direccíon de Ethereum* ya está en tu lista',
           'TXT_ADD_ETH_ADDRESS_WALLET_ADDED': '✅ ¡*La direccíon de Ethereum* añadida con éxito!\n',
           'LINK_SHARE_BOT': 'Compartir el bot',
           'LINK_TEXT_SHARE_BOT': '¡Siempre estarás controlando tu saldo de Ethereum y ERC tokens en tus carteras! 👍',
           'TXT_ETH_ADDRESS': '📌 *Ethereum dirección:* ',
           'TXT_ETH_TOKENS': '📎 *Tokens ERC:*',
           'TXT_ETH_TOKENS_EMPTY': '📎 *Aún no hay ERC tokens*',
           'TXT_DEL_ETH_WALLET': '❌ Elige una *cartera de Ethereum* para borrar:',
           'TXT_NO_ETH_WALLET': 'ℹ ¡No tienes ninguna *cartera de Ethereum*!',
           'TXT_WALLET_UPDATES': '👉 Saldo se ha cambiado:',
           'TXT_START_MSG': '👽 ¡Hola! Soy tu ETHdroid Bot, te ayudo para que siempre sepas el saldo de Ethereum y ERC tokens en tus carteras.'}

# English language (by default)
ENGLISH = {'TXT_USE_START_BUTTON': '🚀 Use the command /start to bot\'s work!',
           'MENU_ADD_ETH_WALLET': 'Add wallet',
           'MENU_DEL_ETH_WALLET': 'Delete wallet',
           'MENU_CHECK_ALL_BALANCE': 'My balance',
           'MENU_BOT_OPTIONS': 'Options',
           'MENU_SHARE_BOT': 'Share the bot',
           'MENU_FEEDBACK': 'Feedback',
           'TXT_USE_KEYBOARD': '📱 Use the bot keyboard, please',
           'TXT_SHARE_BOT': 'Share this bot with your friends! 👇',
           'TXT_FEEDBACK': 'Write your message for the admin:',
           'MENU_GO_BACK': 'Back',
           'TXT_ERROR': '😓 Sorry, I can\'t show you information now. Please, try again later!',
           'TXT_ADD_ETH_NAME_WALLETS_FULL': '🚫 Allow limit is ' + str(NUMBER_WALLETS) + ' *Ethereum wallets*',
           'TXT_ADD_ETH_ADDRESS_WALLET': '➕ Enter the address of your *Ethereum wallet* 0x...',
           'TXT_ADD_ETH_ADDRESS_WALLET_WRONG': '🚩 This *Ethereum address* is not correct, try another one 0x...',
           'TXT_ADD_ETH_ADDRESS_WALLET_EXISTS': '📌 This *Ethereum address* has been already added earlier',
           'TXT_ADD_ETH_ADDRESS_WALLET_ADDED': '✅ *The Ethereum address* has been added successfully!\n',
           'LINK_SHARE_BOT': 'Share the bot',
           'LINK_TEXT_SHARE_BOT': 'Stay informed of the balance of Ethereum and ERC tokens on yours wallets! 👍',
           'TXT_ETH_ADDRESS': '📌 *Ethereum address:* ',
           'TXT_ETH_TOKENS': '📎 *Tokens ERC*:',
           'TXT_ETH_TOKENS_EMPTY': '📎 *There is not any token ERC yet*',
           'TXT_DEL_ETH_WALLET': '❌ Choose a *Ethereum wallet* for delete:',
           'TXT_NO_ETH_WALLET': 'ℹ There is no *Ethereum wallet*!',
           'TXT_WALLET_UPDATES': '👉 Balance changed:',
           'TXT_START_MSG': '👽 Hello! I am your ETHdroid Bot, I will help you '
                            'to control the balance of Ethereum and ERC tokens on yours wallets.'}
